//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Personal_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImage
    {
        public int ImageID { get; set; }
        public string ImageUrl { get; set; }
        public string ImageDescription { get; set; }
    }
}
